
input_params = {'vin': 13.2,
                'vout': 5,
                'pin': 5*16, 
                'eff': 1,
                'fs':375e3,
                'tambient':65,
                'controller':'raa489300',
                'lout':{'family':'cmll063t',
                        'value(uH)':0.4,
                        'config':'single'},
                'lvl_config':'3 level',
                'hsfet_partnum':'SISH536DN',
                'lsfet_partnum':'SISS52DN',
                'vgate':5,
                'm_hs':1,
                'm_ls':1,
                'rd':0.5,
                'caps':{'vin'   :{'partnum':'GRM188C81C106MA73','n':4},
                        'vout'  :{'partnum':'GRM155C80J106ME11D','n':10},
                        'flying':{'partnum':'GRM188C81C106MA73','n':4}}
               }

input_params = {'vin': 48,
                'vout': 20,
                'pin': 241,
                'eff': 1,
                'fs':315e3,
                'tambient':45,
                'controller':'raa489300',
                'lout':{'family':'hbed053t',
                        'value(uH)':1.0,
                        'config':'single'},
                'lvl_config':'3 level',
                'hsfet_partnum':'ISZ0702NLS',
                'lsfet_partnum':'BSZ024N04LS6',
                'q4_partnum':'SHORT',
                'vgate':10,
                'm_hs':1,
                'm_ls':1,
                'rd':0.5,
                'caps':{'vin'   :{'partnum':'GRM32EC72A106KE05L','n':4},
                        'vout'  :{'partnum':'GRM32EC72A106KE05L','n':8},
                        'flying':{'partnum':'C2012X5R1H106K125AC','n':8}}

